package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CertificadosEmpresas generated by hbm2java
 */
public class CertificadosEmpresas  implements java.io.Serializable {


     private Integer idCertificado;
     private Empresas empresas;
     private String pfx;
     private String passwd;
     private Date vigenciaCertificado;
     private String expiracionCertificado;
     private Set tokens = new HashSet(0);

    public CertificadosEmpresas() {
    }

	
    public CertificadosEmpresas(Empresas empresas, String pfx, String passwd, Date vigenciaCertificado, String expiracionCertificado) {
        this.empresas = empresas;
        this.pfx = pfx;
        this.passwd = passwd;
        this.vigenciaCertificado = vigenciaCertificado;
        this.expiracionCertificado = expiracionCertificado;
    }
    public CertificadosEmpresas(Empresas empresas, String pfx, String passwd, Date vigenciaCertificado, String expiracionCertificado, Set tokens) {
       this.empresas = empresas;
       this.pfx = pfx;
       this.passwd = passwd;
       this.vigenciaCertificado = vigenciaCertificado;
       this.expiracionCertificado = expiracionCertificado;
       this.tokens = tokens;
    }
   
    public Integer getIdCertificado() {
        return this.idCertificado;
    }
    
    public void setIdCertificado(Integer idCertificado) {
        this.idCertificado = idCertificado;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getPfx() {
        return this.pfx;
    }
    
    public void setPfx(String pfx) {
        this.pfx = pfx;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public Date getVigenciaCertificado() {
        return this.vigenciaCertificado;
    }
    
    public void setVigenciaCertificado(Date vigenciaCertificado) {
        this.vigenciaCertificado = vigenciaCertificado;
    }
    public String getExpiracionCertificado() {
        return this.expiracionCertificado;
    }
    
    public void setExpiracionCertificado(String expiracionCertificado) {
        this.expiracionCertificado = expiracionCertificado;
    }
    public Set getTokens() {
        return this.tokens;
    }
    
    public void setTokens(Set tokens) {
        this.tokens = tokens;
    }




}


