package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1



/**
 * Configuraciones generated by hbm2java
 */
public class Configuraciones  implements java.io.Serializable {


     private Integer idConfiguraciones;
     private Empresas empresas;
     private String propiedad;
     private String valor;
     private String descripcion;
     private String tipo;

    public Configuraciones() {
    }

	
    public Configuraciones(Empresas empresas) {
        this.empresas = empresas;
    }
    public Configuraciones(Empresas empresas, String propiedad, String valor, String descripcion, String tipo) {
       this.empresas = empresas;
       this.propiedad = propiedad;
       this.valor = valor;
       this.descripcion = descripcion;
       this.tipo = tipo;
    }
   
    public Integer getIdConfiguraciones() {
        return this.idConfiguraciones;
    }
    
    public void setIdConfiguraciones(Integer idConfiguraciones) {
        this.idConfiguraciones = idConfiguraciones;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getPropiedad() {
        return this.propiedad;
    }
    
    public void setPropiedad(String propiedad) {
        this.propiedad = propiedad;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


