package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ControlDescargas generated by hbm2java
 */
public class ControlDescargas  implements java.io.Serializable {


     private Integer idControlDescargas;
     private Empresas empresas;
     private Date fechaDescargaInicial;
     private Date fechaDescargaFinal;
     private String tipoDescargaRegistro;
     private String contadorSolicitudesDescargadas;
     private String tipoPeticionDescarga;
     private String frecuenciaDescarga;
     private String estadoFinal;
     private String informe;

    public ControlDescargas() {
    }

	
    public ControlDescargas(Empresas empresas) {
        this.empresas = empresas;
    }
    public ControlDescargas(Empresas empresas, Date fechaDescargaInicial, Date fechaDescargaFinal, String tipoDescargaRegistro, String contadorSolicitudesDescargadas, String tipoPeticionDescarga, String frecuenciaDescarga, String estadoFinal, String informe) {
       this.empresas = empresas;
       this.fechaDescargaInicial = fechaDescargaInicial;
       this.fechaDescargaFinal = fechaDescargaFinal;
       this.tipoDescargaRegistro = tipoDescargaRegistro;
       this.contadorSolicitudesDescargadas = contadorSolicitudesDescargadas;
       this.tipoPeticionDescarga = tipoPeticionDescarga;
       this.frecuenciaDescarga = frecuenciaDescarga;
       this.estadoFinal = estadoFinal;
       this.informe = informe;
    }
   
    public Integer getIdControlDescargas() {
        return this.idControlDescargas;
    }
    
    public void setIdControlDescargas(Integer idControlDescargas) {
        this.idControlDescargas = idControlDescargas;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public Date getFechaDescargaInicial() {
        return this.fechaDescargaInicial;
    }
    
    public void setFechaDescargaInicial(Date fechaDescargaInicial) {
        this.fechaDescargaInicial = fechaDescargaInicial;
    }
    public Date getFechaDescargaFinal() {
        return this.fechaDescargaFinal;
    }
    
    public void setFechaDescargaFinal(Date fechaDescargaFinal) {
        this.fechaDescargaFinal = fechaDescargaFinal;
    }
    public String getTipoDescargaRegistro() {
        return this.tipoDescargaRegistro;
    }
    
    public void setTipoDescargaRegistro(String tipoDescargaRegistro) {
        this.tipoDescargaRegistro = tipoDescargaRegistro;
    }
    public String getContadorSolicitudesDescargadas() {
        return this.contadorSolicitudesDescargadas;
    }
    
    public void setContadorSolicitudesDescargadas(String contadorSolicitudesDescargadas) {
        this.contadorSolicitudesDescargadas = contadorSolicitudesDescargadas;
    }
    public String getTipoPeticionDescarga() {
        return this.tipoPeticionDescarga;
    }
    
    public void setTipoPeticionDescarga(String tipoPeticionDescarga) {
        this.tipoPeticionDescarga = tipoPeticionDescarga;
    }
    public String getFrecuenciaDescarga() {
        return this.frecuenciaDescarga;
    }
    
    public void setFrecuenciaDescarga(String frecuenciaDescarga) {
        this.frecuenciaDescarga = frecuenciaDescarga;
    }
    public String getEstadoFinal() {
        return this.estadoFinal;
    }
    
    public void setEstadoFinal(String estadoFinal) {
        this.estadoFinal = estadoFinal;
    }
    public String getInforme() {
        return this.informe;
    }
    
    public void setInforme(String informe) {
        this.informe = informe;
    }




}


