package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * MetadatosSinCfdiEmitido generated by hbm2java
 */
public class MetadatosSinCfdiEmitido implements java.io.Serializable {

    private Integer idMetadato;
    private String uuid;
    private String rfcEmisor;
    private String nombreEmisor;
    private String rfcReceptor;
    private String nombreReceptor;
    private String rfcPac;
    private Date fechaEmision;
    private Date fechaCertificacionSat;
    private BigDecimal monto;
    private String efectoComprobante;
    private boolean estatus;
    private Date fechaCancelacion;
    private String estadoMd;
    private String descripcionError;

    public MetadatosSinCfdiEmitido() {
    }

    public MetadatosSinCfdiEmitido(String uuid, String rfcEmisor, String nombreEmisor, String rfcReceptor, String nombreReceptor, String rfcPac, Date fechaEmision, Date fechaCertificacionSat, BigDecimal monto, String efectoComprobante, boolean estatus) {
        this.uuid = uuid;
        this.rfcEmisor = rfcEmisor;
        this.nombreEmisor = nombreEmisor;
        this.rfcReceptor = rfcReceptor;
        this.nombreReceptor = nombreReceptor;
        this.rfcPac = rfcPac;
        this.fechaEmision = fechaEmision;
        this.fechaCertificacionSat = fechaCertificacionSat;
        this.monto = monto;
        this.efectoComprobante = efectoComprobante;
        this.estatus = estatus;
    }

    public MetadatosSinCfdiEmitido(String uuid, String rfcEmisor, String nombreEmisor, String rfcReceptor, String nombreReceptor, String rfcPac, Date fechaEmision, Date fechaCertificacionSat, BigDecimal monto, String efectoComprobante, boolean estatus, Date fechaCancelacion, String estadoMd, String descripcionError) {
        this.uuid = uuid;
        this.rfcEmisor = rfcEmisor;
        this.nombreEmisor = nombreEmisor;
        this.rfcReceptor = rfcReceptor;
        this.nombreReceptor = nombreReceptor;
        this.rfcPac = rfcPac;
        this.fechaEmision = fechaEmision;
        this.fechaCertificacionSat = fechaCertificacionSat;
        this.monto = monto;
        this.efectoComprobante = efectoComprobante;
        this.estatus = estatus;
        this.fechaCancelacion = fechaCancelacion;
        this.estadoMd = estadoMd;
        this.descripcionError = descripcionError;
    }

    public Integer getIdMetadato() {
        return this.idMetadato;
    }

    public void setIdMetadato(Integer idMetadato) {
        this.idMetadato = idMetadato;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public String getRfcEmisor() {
        return this.rfcEmisor;
    }

    public void setRfcEmisor(String rfcEmisor) {
        this.rfcEmisor = rfcEmisor;
    }

    public String getNombreEmisor() {
        return this.nombreEmisor;
    }

    public void setNombreEmisor(String nombreEmisor) {
        this.nombreEmisor = nombreEmisor;
    }

    public String getRfcReceptor() {
        return this.rfcReceptor;
    }

    public void setRfcReceptor(String rfcReceptor) {
        this.rfcReceptor = rfcReceptor;
    }

    public String getNombreReceptor() {
        return this.nombreReceptor;
    }

    public void setNombreReceptor(String nombreReceptor) {
        this.nombreReceptor = nombreReceptor;
    }

    public String getRfcPac() {
        return this.rfcPac;
    }

    public void setRfcPac(String rfcPac) {
        this.rfcPac = rfcPac;
    }

    public Date getFechaEmision() {
        return this.fechaEmision;
    }

    public void setFechaEmision(Date fechaEmision) {
        this.fechaEmision = fechaEmision;
    }

    public Date getFechaCertificacionSat() {
        return this.fechaCertificacionSat;
    }

    public void setFechaCertificacionSat(Date fechaCertificacionSat) {
        this.fechaCertificacionSat = fechaCertificacionSat;
    }

    public BigDecimal getMonto() {
        return this.monto;
    }

    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    public String getEfectoComprobante() {
        return this.efectoComprobante;
    }

    public void setEfectoComprobante(String efectoComprobante) {
        this.efectoComprobante = efectoComprobante;
    }

    public boolean isEstatus() {
        return this.estatus;
    }

    public void setEstatus(boolean estatus) {
        this.estatus = estatus;
    }

    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }

    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }

    public String getEstadoMd() {
        return this.estadoMd;
    }

    public void setEstadoMd(String estadoMd) {
        this.estadoMd = estadoMd;
    }

    public String getDescripcionError() {
        return this.descripcionError;
    }

    public void setDescripcionError(String descripcionError) {
        this.descripcionError = descripcionError;
    }

}
