package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1



/**
 * RegistroMetadataFile generated by hbm2java
 */
public class RegistroMetadataFile  implements java.io.Serializable {


     private Integer idRegistroMetadataFile;
     private RegistroPeticionesEmpresa registroPeticionesEmpresa;
     private String nameFileZip;
     private String nameFileTxt;
     private String estatus;
     private String tipoError;

    public RegistroMetadataFile() {
    }

	
    public RegistroMetadataFile(RegistroPeticionesEmpresa registroPeticionesEmpresa, String nameFileZip, String nameFileTxt) {
        this.registroPeticionesEmpresa = registroPeticionesEmpresa;
        this.nameFileZip = nameFileZip;
        this.nameFileTxt = nameFileTxt;
    }
    public RegistroMetadataFile(RegistroPeticionesEmpresa registroPeticionesEmpresa, String nameFileZip, String nameFileTxt, String estatus, String tipoError) {
       this.registroPeticionesEmpresa = registroPeticionesEmpresa;
       this.nameFileZip = nameFileZip;
       this.nameFileTxt = nameFileTxt;
       this.estatus = estatus;
       this.tipoError = tipoError;
    }
   
    public Integer getIdRegistroMetadataFile() {
        return this.idRegistroMetadataFile;
    }
    
    public void setIdRegistroMetadataFile(Integer idRegistroMetadataFile) {
        this.idRegistroMetadataFile = idRegistroMetadataFile;
    }
    public RegistroPeticionesEmpresa getRegistroPeticionesEmpresa() {
        return this.registroPeticionesEmpresa;
    }
    
    public void setRegistroPeticionesEmpresa(RegistroPeticionesEmpresa registroPeticionesEmpresa) {
        this.registroPeticionesEmpresa = registroPeticionesEmpresa;
    }
    public String getNameFileZip() {
        return this.nameFileZip;
    }
    
    public void setNameFileZip(String nameFileZip) {
        this.nameFileZip = nameFileZip;
    }
    public String getNameFileTxt() {
        return this.nameFileTxt;
    }
    
    public void setNameFileTxt(String nameFileTxt) {
        this.nameFileTxt = nameFileTxt;
    }
    public String getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(String estatus) {
        this.estatus = estatus;
    }
    public String getTipoError() {
        return this.tipoError;
    }
    
    public void setTipoError(String tipoError) {
        this.tipoError = tipoError;
    }




}


