package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RegistroPeticionesEmpresa generated by hbm2java
 */
public class RegistroPeticionesEmpresa  implements java.io.Serializable {


     private Integer idPeticion;
     private Empresas empresas;
     private String codigoPeticion;
     private String tipoProceso;
     private String tipoPeticion;
     private String endToEmit;
     private String tipoFormato;
     private String estadoPeticionBd;
     private Integer noXmlmed;
     private Character estadoSolicitudSat;
     private String respuestaError;
     private Date fechaInicial;
     private Date fechaFinal;
     private Date fechaPeticion;
     private Character estadoDescarga;
     private Integer noIntentos;
     private Set registroMetadataFiles = new HashSet(0);

    public RegistroPeticionesEmpresa() {
    }

	
    public RegistroPeticionesEmpresa(Empresas empresas) {
        this.empresas = empresas;
    }
    public RegistroPeticionesEmpresa(Empresas empresas, String codigoPeticion, String tipoProceso, String tipoPeticion, String endToEmit, String tipoFormato, String estadoPeticionBd, Integer noXmlmed, Character estadoSolicitudSat, String respuestaError, Date fechaInicial, Date fechaFinal, Date fechaPeticion, Character estadoDescarga, Integer noIntentos, Set registroMetadataFiles) {
       this.empresas = empresas;
       this.codigoPeticion = codigoPeticion;
       this.tipoProceso = tipoProceso;
       this.tipoPeticion = tipoPeticion;
       this.endToEmit = endToEmit;
       this.tipoFormato = tipoFormato;
       this.estadoPeticionBd = estadoPeticionBd;
       this.noXmlmed = noXmlmed;
       this.estadoSolicitudSat = estadoSolicitudSat;
       this.respuestaError = respuestaError;
       this.fechaInicial = fechaInicial;
       this.fechaFinal = fechaFinal;
       this.fechaPeticion = fechaPeticion;
       this.estadoDescarga = estadoDescarga;
       this.noIntentos = noIntentos;
       this.registroMetadataFiles = registroMetadataFiles;
    }
   
    public Integer getIdPeticion() {
        return this.idPeticion;
    }
    
    public void setIdPeticion(Integer idPeticion) {
        this.idPeticion = idPeticion;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public String getCodigoPeticion() {
        return this.codigoPeticion;
    }
    
    public void setCodigoPeticion(String codigoPeticion) {
        this.codigoPeticion = codigoPeticion;
    }
    public String getTipoProceso() {
        return this.tipoProceso;
    }
    
    public void setTipoProceso(String tipoProceso) {
        this.tipoProceso = tipoProceso;
    }
    public String getTipoPeticion() {
        return this.tipoPeticion;
    }
    
    public void setTipoPeticion(String tipoPeticion) {
        this.tipoPeticion = tipoPeticion;
    }
    public String getEndToEmit() {
        return this.endToEmit;
    }
    
    public void setEndToEmit(String endToEmit) {
        this.endToEmit = endToEmit;
    }
    public String getTipoFormato() {
        return this.tipoFormato;
    }
    
    public void setTipoFormato(String tipoFormato) {
        this.tipoFormato = tipoFormato;
    }
    public String getEstadoPeticionBd() {
        return this.estadoPeticionBd;
    }
    
    public void setEstadoPeticionBd(String estadoPeticionBd) {
        this.estadoPeticionBd = estadoPeticionBd;
    }
    public Integer getNoXmlmed() {
        return this.noXmlmed;
    }
    
    public void setNoXmlmed(Integer noXmlmed) {
        this.noXmlmed = noXmlmed;
    }
    public Character getEstadoSolicitudSat() {
        return this.estadoSolicitudSat;
    }
    
    public void setEstadoSolicitudSat(Character estadoSolicitudSat) {
        this.estadoSolicitudSat = estadoSolicitudSat;
    }
    public String getRespuestaError() {
        return this.respuestaError;
    }
    
    public void setRespuestaError(String respuestaError) {
        this.respuestaError = respuestaError;
    }
    public Date getFechaInicial() {
        return this.fechaInicial;
    }
    
    public void setFechaInicial(Date fechaInicial) {
        this.fechaInicial = fechaInicial;
    }
    public Date getFechaFinal() {
        return this.fechaFinal;
    }
    
    public void setFechaFinal(Date fechaFinal) {
        this.fechaFinal = fechaFinal;
    }
    public Date getFechaPeticion() {
        return this.fechaPeticion;
    }
    
    public void setFechaPeticion(Date fechaPeticion) {
        this.fechaPeticion = fechaPeticion;
    }
    public Character getEstadoDescarga() {
        return this.estadoDescarga;
    }
    
    public void setEstadoDescarga(Character estadoDescarga) {
        this.estadoDescarga = estadoDescarga;
    }
    public Integer getNoIntentos() {
        return this.noIntentos;
    }
    
    public void setNoIntentos(Integer noIntentos) {
        this.noIntentos = noIntentos;
    }
    public Set getRegistroMetadataFiles() {
        return this.registroMetadataFiles;
    }
    
    public void setRegistroMetadataFiles(Set registroMetadataFiles) {
        this.registroMetadataFiles = registroMetadataFiles;
    }




}


