package com.iq.pojos.descarga;
// Generated Apr 27, 2024 2:09:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Token generated by hbm2java
 */
public class Token  implements java.io.Serializable {


     private Integer idToken;
     private CertificadosEmpresas certificadosEmpresas;
     private String tokenAcceso;
     private Date vigenciaToken;
     private String expiracionToken;

    public Token() {
    }

	
    public Token(CertificadosEmpresas certificadosEmpresas) {
        this.certificadosEmpresas = certificadosEmpresas;
    }
    public Token(CertificadosEmpresas certificadosEmpresas, String tokenAcceso, Date vigenciaToken, String expiracionToken) {
       this.certificadosEmpresas = certificadosEmpresas;
       this.tokenAcceso = tokenAcceso;
       this.vigenciaToken = vigenciaToken;
       this.expiracionToken = expiracionToken;
    }
   
    public Integer getIdToken() {
        return this.idToken;
    }
    
    public void setIdToken(Integer idToken) {
        this.idToken = idToken;
    }
    public CertificadosEmpresas getCertificadosEmpresas() {
        return this.certificadosEmpresas;
    }
    
    public void setCertificadosEmpresas(CertificadosEmpresas certificadosEmpresas) {
        this.certificadosEmpresas = certificadosEmpresas;
    }
    public String getTokenAcceso() {
        return this.tokenAcceso;
    }
    
    public void setTokenAcceso(String tokenAcceso) {
        this.tokenAcceso = tokenAcceso;
    }
    public Date getVigenciaToken() {
        return this.vigenciaToken;
    }
    
    public void setVigenciaToken(Date vigenciaToken) {
        this.vigenciaToken = vigenciaToken;
    }
    public String getExpiracionToken() {
        return this.expiracionToken;
    }
    
    public void setExpiracionToken(String expiracionToken) {
        this.expiracionToken = expiracionToken;
    }




}


