package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * Cce11MotivoTraslado generated by hbm2java
 */
public class Cce11MotivoTraslado  implements java.io.Serializable {


     private Integer idMotivoTraslado;
     private String claveMotivoTraslado;

    public Cce11MotivoTraslado() {
    }

    public Cce11MotivoTraslado(String claveMotivoTraslado) {
       this.claveMotivoTraslado = claveMotivoTraslado;
    }
   
    public Integer getIdMotivoTraslado() {
        return this.idMotivoTraslado;
    }
    
    public void setIdMotivoTraslado(Integer idMotivoTraslado) {
        this.idMotivoTraslado = idMotivoTraslado;
    }
    public String getClaveMotivoTraslado() {
        return this.claveMotivoTraslado;
    }
    
    public void setClaveMotivoTraslado(String claveMotivoTraslado) {
        this.claveMotivoTraslado = claveMotivoTraslado;
    }




}


