package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CfdsRetenciones generated by hbm2java
 */
public class CfdsRetenciones  implements java.io.Serializable {


     private Integer id;
     private RetencionesPlantillas retencionesPlantillas;
     private int idSucursal;
     private int idTipocfdRetenciones;
     private String rfcEmisor;
     private String rfcReceptor;
     private Date fechaModificacion;
     private Date fechaRecepcion;
     private Date fechaGeneracion;
     private Date fechaCancelacion;
     private Date fechaRetencion;
     private String uuid;
     private BigDecimal totalOperacion;
     private BigDecimal totalRetencion;
     private String estadoFiscal;
     private String estado;
     private String cadenaOriginal;
     private Set xmlsRetencioneses = new HashSet(0);
     private Set clientesValoresSmtpRetencioneses = new HashSet(0);
     private Set receptorRetencioneses = new HashSet(0);

    public CfdsRetenciones() {
    }

	
    public CfdsRetenciones(int idSucursal, int idTipocfdRetenciones, Date fechaModificacion, Date fechaRecepcion, Date fechaGeneracion, Date fechaRetencion, String uuid, BigDecimal totalOperacion, BigDecimal totalRetencion) {
        this.idSucursal = idSucursal;
        this.idTipocfdRetenciones = idTipocfdRetenciones;
        this.fechaModificacion = fechaModificacion;
        this.fechaRecepcion = fechaRecepcion;
        this.fechaGeneracion = fechaGeneracion;
        this.fechaRetencion = fechaRetencion;
        this.uuid = uuid;
        this.totalOperacion = totalOperacion;
        this.totalRetencion = totalRetencion;
    }
    public CfdsRetenciones(RetencionesPlantillas retencionesPlantillas, int idSucursal, int idTipocfdRetenciones, String rfcEmisor, String rfcReceptor, Date fechaModificacion, Date fechaRecepcion, Date fechaGeneracion, Date fechaCancelacion, Date fechaRetencion, String uuid, BigDecimal totalOperacion, BigDecimal totalRetencion, String estadoFiscal, String estado, String cadenaOriginal, Set xmlsRetencioneses, Set clientesValoresSmtpRetencioneses, Set receptorRetencioneses) {
       this.retencionesPlantillas = retencionesPlantillas;
       this.idSucursal = idSucursal;
       this.idTipocfdRetenciones = idTipocfdRetenciones;
       this.rfcEmisor = rfcEmisor;
       this.rfcReceptor = rfcReceptor;
       this.fechaModificacion = fechaModificacion;
       this.fechaRecepcion = fechaRecepcion;
       this.fechaGeneracion = fechaGeneracion;
       this.fechaCancelacion = fechaCancelacion;
       this.fechaRetencion = fechaRetencion;
       this.uuid = uuid;
       this.totalOperacion = totalOperacion;
       this.totalRetencion = totalRetencion;
       this.estadoFiscal = estadoFiscal;
       this.estado = estado;
       this.cadenaOriginal = cadenaOriginal;
       this.xmlsRetencioneses = xmlsRetencioneses;
       this.clientesValoresSmtpRetencioneses = clientesValoresSmtpRetencioneses;
       this.receptorRetencioneses = receptorRetencioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RetencionesPlantillas getRetencionesPlantillas() {
        return this.retencionesPlantillas;
    }
    
    public void setRetencionesPlantillas(RetencionesPlantillas retencionesPlantillas) {
        this.retencionesPlantillas = retencionesPlantillas;
    }
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public int getIdTipocfdRetenciones() {
        return this.idTipocfdRetenciones;
    }
    
    public void setIdTipocfdRetenciones(int idTipocfdRetenciones) {
        this.idTipocfdRetenciones = idTipocfdRetenciones;
    }
    public String getRfcEmisor() {
        return this.rfcEmisor;
    }
    
    public void setRfcEmisor(String rfcEmisor) {
        this.rfcEmisor = rfcEmisor;
    }
    public String getRfcReceptor() {
        return this.rfcReceptor;
    }
    
    public void setRfcReceptor(String rfcReceptor) {
        this.rfcReceptor = rfcReceptor;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public Date getFechaGeneracion() {
        return this.fechaGeneracion;
    }
    
    public void setFechaGeneracion(Date fechaGeneracion) {
        this.fechaGeneracion = fechaGeneracion;
    }
    public Date getFechaCancelacion() {
        return this.fechaCancelacion;
    }
    
    public void setFechaCancelacion(Date fechaCancelacion) {
        this.fechaCancelacion = fechaCancelacion;
    }
    public Date getFechaRetencion() {
        return this.fechaRetencion;
    }
    
    public void setFechaRetencion(Date fechaRetencion) {
        this.fechaRetencion = fechaRetencion;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public BigDecimal getTotalOperacion() {
        return this.totalOperacion;
    }
    
    public void setTotalOperacion(BigDecimal totalOperacion) {
        this.totalOperacion = totalOperacion;
    }
    public BigDecimal getTotalRetencion() {
        return this.totalRetencion;
    }
    
    public void setTotalRetencion(BigDecimal totalRetencion) {
        this.totalRetencion = totalRetencion;
    }
    public String getEstadoFiscal() {
        return this.estadoFiscal;
    }
    
    public void setEstadoFiscal(String estadoFiscal) {
        this.estadoFiscal = estadoFiscal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCadenaOriginal() {
        return this.cadenaOriginal;
    }
    
    public void setCadenaOriginal(String cadenaOriginal) {
        this.cadenaOriginal = cadenaOriginal;
    }
    public Set getXmlsRetencioneses() {
        return this.xmlsRetencioneses;
    }
    
    public void setXmlsRetencioneses(Set xmlsRetencioneses) {
        this.xmlsRetencioneses = xmlsRetencioneses;
    }
    public Set getClientesValoresSmtpRetencioneses() {
        return this.clientesValoresSmtpRetencioneses;
    }
    
    public void setClientesValoresSmtpRetencioneses(Set clientesValoresSmtpRetencioneses) {
        this.clientesValoresSmtpRetencioneses = clientesValoresSmtpRetencioneses;
    }
    public Set getReceptorRetencioneses() {
        return this.receptorRetencioneses;
    }
    
    public void setReceptorRetencioneses(Set receptorRetencioneses) {
        this.receptorRetencioneses = receptorRetencioneses;
    }




}


