package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CfdsRetencionesTest generated by hbm2java
 */
public class CfdsRetencionesTest  implements java.io.Serializable {


     private Integer idCfdRetencionTest;
     private TiposCfdRetenciones tiposCfdRetenciones;
     private Date dateInsert;
     private int idEmpresa;
     private String uuid;
     private Integer idPlantilla;
     private String rfcEmisor;
     private String rfcReceptor;
     private Set xmlsRetencionesTests = new HashSet(0);

    public CfdsRetencionesTest() {
    }

	
    public CfdsRetencionesTest(TiposCfdRetenciones tiposCfdRetenciones, Date dateInsert, int idEmpresa, String uuid, String rfcEmisor, String rfcReceptor) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
        this.dateInsert = dateInsert;
        this.idEmpresa = idEmpresa;
        this.uuid = uuid;
        this.rfcEmisor = rfcEmisor;
        this.rfcReceptor = rfcReceptor;
    }
    public CfdsRetencionesTest(TiposCfdRetenciones tiposCfdRetenciones, Date dateInsert, int idEmpresa, String uuid, Integer idPlantilla, String rfcEmisor, String rfcReceptor, Set xmlsRetencionesTests) {
       this.tiposCfdRetenciones = tiposCfdRetenciones;
       this.dateInsert = dateInsert;
       this.idEmpresa = idEmpresa;
       this.uuid = uuid;
       this.idPlantilla = idPlantilla;
       this.rfcEmisor = rfcEmisor;
       this.rfcReceptor = rfcReceptor;
       this.xmlsRetencionesTests = xmlsRetencionesTests;
    }
   
    public Integer getIdCfdRetencionTest() {
        return this.idCfdRetencionTest;
    }
    
    public void setIdCfdRetencionTest(Integer idCfdRetencionTest) {
        this.idCfdRetencionTest = idCfdRetencionTest;
    }
    public TiposCfdRetenciones getTiposCfdRetenciones() {
        return this.tiposCfdRetenciones;
    }
    
    public void setTiposCfdRetenciones(TiposCfdRetenciones tiposCfdRetenciones) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
    }
    public Date getDateInsert() {
        return this.dateInsert;
    }
    
    public void setDateInsert(Date dateInsert) {
        this.dateInsert = dateInsert;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Integer getIdPlantilla() {
        return this.idPlantilla;
    }
    
    public void setIdPlantilla(Integer idPlantilla) {
        this.idPlantilla = idPlantilla;
    }
    public String getRfcEmisor() {
        return this.rfcEmisor;
    }
    
    public void setRfcEmisor(String rfcEmisor) {
        this.rfcEmisor = rfcEmisor;
    }
    public String getRfcReceptor() {
        return this.rfcReceptor;
    }
    
    public void setRfcReceptor(String rfcReceptor) {
        this.rfcReceptor = rfcReceptor;
    }
    public Set getXmlsRetencionesTests() {
        return this.xmlsRetencionesTests;
    }
    
    public void setXmlsRetencionesTests(Set xmlsRetencionesTests) {
        this.xmlsRetencionesTests = xmlsRetencionesTests;
    }




}


