package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * ClientesValoresSmtp generated by hbm2java
 */
public class ClientesValoresSmtp  implements java.io.Serializable {


     private int idCliente;
     private Clientes clientes;
     private String para;
     private String asunto;
     private String cuerpoMensaje;
     private boolean pdf;
     private boolean xml;
     private String alternativo;
     private boolean general;
     private Byte zipFormat;

    public ClientesValoresSmtp() {
    }

	
    public ClientesValoresSmtp(int idCliente, Clientes clientes, boolean pdf, boolean xml, boolean general) {
        this.idCliente = idCliente;
        this.clientes = clientes;
        this.pdf = pdf;
        this.xml = xml;
        this.general = general;
    }
    public ClientesValoresSmtp(int idCliente, Clientes clientes, String para, String asunto, String cuerpoMensaje, boolean pdf, boolean xml, String alternativo, boolean general, Byte zipFormat) {
       this.idCliente = idCliente;
       this.clientes = clientes;
       this.para = para;
       this.asunto = asunto;
       this.cuerpoMensaje = cuerpoMensaje;
       this.pdf = pdf;
       this.xml = xml;
       this.alternativo = alternativo;
       this.general = general;
       this.zipFormat = zipFormat;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getPara() {
        return this.para;
    }
    
    public void setPara(String para) {
        this.para = para;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getCuerpoMensaje() {
        return this.cuerpoMensaje;
    }
    
    public void setCuerpoMensaje(String cuerpoMensaje) {
        this.cuerpoMensaje = cuerpoMensaje;
    }
    public boolean isPdf() {
        return this.pdf;
    }
    
    public void setPdf(boolean pdf) {
        this.pdf = pdf;
    }
    public boolean isXml() {
        return this.xml;
    }
    
    public void setXml(boolean xml) {
        this.xml = xml;
    }
    public String getAlternativo() {
        return this.alternativo;
    }
    
    public void setAlternativo(String alternativo) {
        this.alternativo = alternativo;
    }
    public boolean isGeneral() {
        return this.general;
    }
    
    public void setGeneral(boolean general) {
        this.general = general;
    }
    public Byte getZipFormat() {
        return this.zipFormat;
    }
    
    public void setZipFormat(Byte zipFormat) {
        this.zipFormat = zipFormat;
    }




}


