package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * ClientesValoresSmtpRetenciones generated by hbm2java
 */
public class ClientesValoresSmtpRetenciones  implements java.io.Serializable {


     private int idRetenciones;
     private CfdsRetenciones cfdsRetenciones;
     private String para;
     private String asunto;
     private String cuerpoMensaje;
     private Boolean pdf;
     private Boolean xml;
     private String alternativo;
     private Boolean general;
     private Boolean zipFormat;

    public ClientesValoresSmtpRetenciones() {
    }

	
    public ClientesValoresSmtpRetenciones(int idRetenciones, CfdsRetenciones cfdsRetenciones) {
        this.idRetenciones = idRetenciones;
        this.cfdsRetenciones = cfdsRetenciones;
    }
    public ClientesValoresSmtpRetenciones(int idRetenciones, CfdsRetenciones cfdsRetenciones, String para, String asunto, String cuerpoMensaje, Boolean pdf, Boolean xml, String alternativo, Boolean general, Boolean zipFormat) {
       this.idRetenciones = idRetenciones;
       this.cfdsRetenciones = cfdsRetenciones;
       this.para = para;
       this.asunto = asunto;
       this.cuerpoMensaje = cuerpoMensaje;
       this.pdf = pdf;
       this.xml = xml;
       this.alternativo = alternativo;
       this.general = general;
       this.zipFormat = zipFormat;
    }
   
    public int getIdRetenciones() {
        return this.idRetenciones;
    }
    
    public void setIdRetenciones(int idRetenciones) {
        this.idRetenciones = idRetenciones;
    }
    public CfdsRetenciones getCfdsRetenciones() {
        return this.cfdsRetenciones;
    }
    
    public void setCfdsRetenciones(CfdsRetenciones cfdsRetenciones) {
        this.cfdsRetenciones = cfdsRetenciones;
    }
    public String getPara() {
        return this.para;
    }
    
    public void setPara(String para) {
        this.para = para;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getCuerpoMensaje() {
        return this.cuerpoMensaje;
    }
    
    public void setCuerpoMensaje(String cuerpoMensaje) {
        this.cuerpoMensaje = cuerpoMensaje;
    }
    public Boolean getPdf() {
        return this.pdf;
    }
    
    public void setPdf(Boolean pdf) {
        this.pdf = pdf;
    }
    public Boolean getXml() {
        return this.xml;
    }
    
    public void setXml(Boolean xml) {
        this.xml = xml;
    }
    public String getAlternativo() {
        return this.alternativo;
    }
    
    public void setAlternativo(String alternativo) {
        this.alternativo = alternativo;
    }
    public Boolean getGeneral() {
        return this.general;
    }
    
    public void setGeneral(Boolean general) {
        this.general = general;
    }
    public Boolean getZipFormat() {
        return this.zipFormat;
    }
    
    public void setZipFormat(Boolean zipFormat) {
        this.zipFormat = zipFormat;
    }




}


