package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ClientesAddendas generated by hbm2java
 */
public class ClientesAddendas  implements java.io.Serializable {


     private Integer idAddenda;
     private Clientes clientes;
     private TiposCfd tiposCfd;
     private String tipo;
     private Date fecha;
     private String adaptador;
     private Integer idAddendaB2b;
     private Date vigencia;
     private Boolean tieneEnvio;

    public ClientesAddendas() {
    }

	
    public ClientesAddendas(Clientes clientes, String tipo, Date fecha, String adaptador) {
        this.clientes = clientes;
        this.tipo = tipo;
        this.fecha = fecha;
        this.adaptador = adaptador;
    }
    public ClientesAddendas(Clientes clientes, TiposCfd tiposCfd, String tipo, Date fecha, String adaptador, Integer idAddendaB2b, Date vigencia, Boolean tieneEnvio) {
       this.clientes = clientes;
       this.tiposCfd = tiposCfd;
       this.tipo = tipo;
       this.fecha = fecha;
       this.adaptador = adaptador;
       this.idAddendaB2b = idAddendaB2b;
       this.vigencia = vigencia;
       this.tieneEnvio = tieneEnvio;
    }
   
    public Integer getIdAddenda() {
        return this.idAddenda;
    }
    
    public void setIdAddenda(Integer idAddenda) {
        this.idAddenda = idAddenda;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getAdaptador() {
        return this.adaptador;
    }
    
    public void setAdaptador(String adaptador) {
        this.adaptador = adaptador;
    }
    public Integer getIdAddendaB2b() {
        return this.idAddendaB2b;
    }
    
    public void setIdAddendaB2b(Integer idAddendaB2b) {
        this.idAddendaB2b = idAddendaB2b;
    }
    public Date getVigencia() {
        return this.vigencia;
    }
    
    public void setVigencia(Date vigencia) {
        this.vigencia = vigencia;
    }
    public Boolean getTieneEnvio() {
        return this.tieneEnvio;
    }
    
    public void setTieneEnvio(Boolean tieneEnvio) {
        this.tieneEnvio = tieneEnvio;
    }




}


