package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ComplementosRetenciones generated by hbm2java
 */
public class ComplementosRetenciones  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String prefijo;
     private String adaptador;
     private Set tiposCfdRetencioneses = new HashSet(0);

    public ComplementosRetenciones() {
    }

	
    public ComplementosRetenciones(String nombre, String prefijo, String adaptador) {
        this.nombre = nombre;
        this.prefijo = prefijo;
        this.adaptador = adaptador;
    }
    public ComplementosRetenciones(String nombre, String prefijo, String adaptador, Set tiposCfdRetencioneses) {
       this.nombre = nombre;
       this.prefijo = prefijo;
       this.adaptador = adaptador;
       this.tiposCfdRetencioneses = tiposCfdRetencioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrefijo() {
        return this.prefijo;
    }
    
    public void setPrefijo(String prefijo) {
        this.prefijo = prefijo;
    }
    public String getAdaptador() {
        return this.adaptador;
    }
    
    public void setAdaptador(String adaptador) {
        this.adaptador = adaptador;
    }
    public Set getTiposCfdRetencioneses() {
        return this.tiposCfdRetencioneses;
    }
    
    public void setTiposCfdRetencioneses(Set tiposCfdRetencioneses) {
        this.tiposCfdRetencioneses = tiposCfdRetencioneses;
    }




}


