package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * ConectorAdaptadorRetenciones generated by hbm2java
 */
public class ConectorAdaptadorRetenciones  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String descripcion;
     private String conector;
     private String adaptador;
     private String estado;
     private Set tiposCfdRetencioneses = new HashSet(0);

    public ConectorAdaptadorRetenciones() {
    }

	
    public ConectorAdaptadorRetenciones(String nombre) {
        this.nombre = nombre;
    }
    public ConectorAdaptadorRetenciones(String nombre, String descripcion, String conector, String adaptador, String estado, Set tiposCfdRetencioneses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.conector = conector;
       this.adaptador = adaptador;
       this.estado = estado;
       this.tiposCfdRetencioneses = tiposCfdRetencioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getConector() {
        return this.conector;
    }
    
    public void setConector(String conector) {
        this.conector = conector;
    }
    public String getAdaptador() {
        return this.adaptador;
    }
    
    public void setAdaptador(String adaptador) {
        this.adaptador = adaptador;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getTiposCfdRetencioneses() {
        return this.tiposCfdRetencioneses;
    }
    
    public void setTiposCfdRetencioneses(Set tiposCfdRetencioneses) {
        this.tiposCfdRetencioneses = tiposCfdRetencioneses;
    }




}


