package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DireccionesEnvio generated by hbm2java
 */
public class DireccionesEnvio  implements java.io.Serializable {


     private Integer idDireccion;
     private Clientes clientes;
     private String clave;
     private String descripcion;
     private String calle;
     private String numExterior;
     private String numInterior;
     private String colonia;
     private String localidad;
     private String referencia;
     private String municipio;
     private String estado;
     private String cp;
     private String pais;
     private Set direccionesValoresSmtps = new HashSet(0);

    public DireccionesEnvio() {
    }

	
    public DireccionesEnvio(Clientes clientes, String clave) {
        this.clientes = clientes;
        this.clave = clave;
    }
    public DireccionesEnvio(Clientes clientes, String clave, String descripcion, String calle, String numExterior, String numInterior, String colonia, String localidad, String referencia, String municipio, String estado, String cp, String pais, Set direccionesValoresSmtps) {
       this.clientes = clientes;
       this.clave = clave;
       this.descripcion = descripcion;
       this.calle = calle;
       this.numExterior = numExterior;
       this.numInterior = numInterior;
       this.colonia = colonia;
       this.localidad = localidad;
       this.referencia = referencia;
       this.municipio = municipio;
       this.estado = estado;
       this.cp = cp;
       this.pais = pais;
       this.direccionesValoresSmtps = direccionesValoresSmtps;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumExterior() {
        return this.numExterior;
    }
    
    public void setNumExterior(String numExterior) {
        this.numExterior = numExterior;
    }
    public String getNumInterior() {
        return this.numInterior;
    }
    
    public void setNumInterior(String numInterior) {
        this.numInterior = numInterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getDireccionesValoresSmtps() {
        return this.direccionesValoresSmtps;
    }
    
    public void setDireccionesValoresSmtps(Set direccionesValoresSmtps) {
        this.direccionesValoresSmtps = direccionesValoresSmtps;
    }




}


