package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * DireccionesValoresSmtp generated by hbm2java
 */
public class DireccionesValoresSmtp  implements java.io.Serializable {


     private int idDireccion;
     private DireccionesEnvio direccionesEnvio;
     private String para;
     private String asunto;
     private String cuerpoMensaje;
     private boolean pdf;
     private boolean xml;
     private String alternativo;
     private boolean general;
     private Byte zipFormat;

    public DireccionesValoresSmtp() {
    }

	
    public DireccionesValoresSmtp(int idDireccion, DireccionesEnvio direccionesEnvio, boolean pdf, boolean xml, boolean general) {
        this.idDireccion = idDireccion;
        this.direccionesEnvio = direccionesEnvio;
        this.pdf = pdf;
        this.xml = xml;
        this.general = general;
    }
    public DireccionesValoresSmtp(int idDireccion, DireccionesEnvio direccionesEnvio, String para, String asunto, String cuerpoMensaje, boolean pdf, boolean xml, String alternativo, boolean general, Byte zipFormat) {
       this.idDireccion = idDireccion;
       this.direccionesEnvio = direccionesEnvio;
       this.para = para;
       this.asunto = asunto;
       this.cuerpoMensaje = cuerpoMensaje;
       this.pdf = pdf;
       this.xml = xml;
       this.alternativo = alternativo;
       this.general = general;
       this.zipFormat = zipFormat;
    }
   
    public int getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(int idDireccion) {
        this.idDireccion = idDireccion;
    }
    public DireccionesEnvio getDireccionesEnvio() {
        return this.direccionesEnvio;
    }
    
    public void setDireccionesEnvio(DireccionesEnvio direccionesEnvio) {
        this.direccionesEnvio = direccionesEnvio;
    }
    public String getPara() {
        return this.para;
    }
    
    public void setPara(String para) {
        this.para = para;
    }
    public String getAsunto() {
        return this.asunto;
    }
    
    public void setAsunto(String asunto) {
        this.asunto = asunto;
    }
    public String getCuerpoMensaje() {
        return this.cuerpoMensaje;
    }
    
    public void setCuerpoMensaje(String cuerpoMensaje) {
        this.cuerpoMensaje = cuerpoMensaje;
    }
    public boolean isPdf() {
        return this.pdf;
    }
    
    public void setPdf(boolean pdf) {
        this.pdf = pdf;
    }
    public boolean isXml() {
        return this.xml;
    }
    
    public void setXml(boolean xml) {
        this.xml = xml;
    }
    public String getAlternativo() {
        return this.alternativo;
    }
    
    public void setAlternativo(String alternativo) {
        this.alternativo = alternativo;
    }
    public boolean isGeneral() {
        return this.general;
    }
    
    public void setGeneral(boolean general) {
        this.general = general;
    }
    public Byte getZipFormat() {
        return this.zipFormat;
    }
    
    public void setZipFormat(Byte zipFormat) {
        this.zipFormat = zipFormat;
    }




}


