package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentosRecibidosRetenciones generated by hbm2java
 */
public class DocumentosRecibidosRetenciones  implements java.io.Serializable {


     private Integer id;
     private TiposCfdRetenciones tiposCfdRetenciones;
     private int idSucursal;
     private Date fechaRecepcion;
     private String archivo;
     private String estado;
     private String nombre;
     private String error;
     private Boolean reportado;
     private String batchUuid;
     private Integer idCfdRetenciones;
     private Integer idGenerator;
     private Integer idCfdRetencionTest;
     private Set erroresGeneracionRetencioneses = new HashSet(0);

    public DocumentosRecibidosRetenciones() {
    }

	
    public DocumentosRecibidosRetenciones(TiposCfdRetenciones tiposCfdRetenciones, int idSucursal, Date fechaRecepcion, String archivo, String batchUuid) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
        this.idSucursal = idSucursal;
        this.fechaRecepcion = fechaRecepcion;
        this.archivo = archivo;
        this.batchUuid = batchUuid;
    }
    public DocumentosRecibidosRetenciones(TiposCfdRetenciones tiposCfdRetenciones, int idSucursal, Date fechaRecepcion, String archivo, String estado, String nombre, String error, Boolean reportado, String batchUuid, Integer idCfdRetenciones, Integer idGenerator, Integer idCfdRetencionTest, Set erroresGeneracionRetencioneses) {
       this.tiposCfdRetenciones = tiposCfdRetenciones;
       this.idSucursal = idSucursal;
       this.fechaRecepcion = fechaRecepcion;
       this.archivo = archivo;
       this.estado = estado;
       this.nombre = nombre;
       this.error = error;
       this.reportado = reportado;
       this.batchUuid = batchUuid;
       this.idCfdRetenciones = idCfdRetenciones;
       this.idGenerator = idGenerator;
       this.idCfdRetencionTest = idCfdRetencionTest;
       this.erroresGeneracionRetencioneses = erroresGeneracionRetencioneses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TiposCfdRetenciones getTiposCfdRetenciones() {
        return this.tiposCfdRetenciones;
    }
    
    public void setTiposCfdRetenciones(TiposCfdRetenciones tiposCfdRetenciones) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
    }
    public int getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(int idSucursal) {
        this.idSucursal = idSucursal;
    }
    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }
    
    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }
    public String getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(String archivo) {
        this.archivo = archivo;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getError() {
        return this.error;
    }
    
    public void setError(String error) {
        this.error = error;
    }
    public Boolean getReportado() {
        return this.reportado;
    }
    
    public void setReportado(Boolean reportado) {
        this.reportado = reportado;
    }
    public String getBatchUuid() {
        return this.batchUuid;
    }
    
    public void setBatchUuid(String batchUuid) {
        this.batchUuid = batchUuid;
    }
    public Integer getIdCfdRetenciones() {
        return this.idCfdRetenciones;
    }
    
    public void setIdCfdRetenciones(Integer idCfdRetenciones) {
        this.idCfdRetenciones = idCfdRetenciones;
    }
    public Integer getIdGenerator() {
        return this.idGenerator;
    }
    
    public void setIdGenerator(Integer idGenerator) {
        this.idGenerator = idGenerator;
    }
    public Integer getIdCfdRetencionTest() {
        return this.idCfdRetencionTest;
    }
    
    public void setIdCfdRetencionTest(Integer idCfdRetencionTest) {
        this.idCfdRetencionTest = idCfdRetencionTest;
    }
    public Set getErroresGeneracionRetencioneses() {
        return this.erroresGeneracionRetencioneses;
    }
    
    public void setErroresGeneracionRetencioneses(Set erroresGeneracionRetencioneses) {
        this.erroresGeneracionRetencioneses = erroresGeneracionRetencioneses;
    }




}


