package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * EmpresasRegimenes generated by hbm2java
 */
public class EmpresasRegimenes  implements java.io.Serializable {


     private EmpresasRegimenesId id;

    public EmpresasRegimenes() {
    }

    public EmpresasRegimenes(EmpresasRegimenesId id) {
       this.id = id;
    }
   
    public EmpresasRegimenesId getId() {
        return this.id;
    }
    
    public void setId(EmpresasRegimenesId id) {
        this.id = id;
    }




}


