package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * EmpresasRegimenesId generated by hbm2java
 */
public class EmpresasRegimenesId  implements java.io.Serializable {


     private int idEmpresas;
     private int idRegimenes;

    public EmpresasRegimenesId() {
    }

    public EmpresasRegimenesId(int idEmpresas, int idRegimenes) {
       this.idEmpresas = idEmpresas;
       this.idRegimenes = idRegimenes;
    }
   
    public int getIdEmpresas() {
        return this.idEmpresas;
    }
    
    public void setIdEmpresas(int idEmpresas) {
        this.idEmpresas = idEmpresas;
    }
    public int getIdRegimenes() {
        return this.idRegimenes;
    }
    
    public void setIdRegimenes(int idRegimenes) {
        this.idRegimenes = idRegimenes;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EmpresasRegimenesId) ) return false;
		 EmpresasRegimenesId castOther = ( EmpresasRegimenesId ) other; 
         
		 return (this.getIdEmpresas()==castOther.getIdEmpresas())
 && (this.getIdRegimenes()==castOther.getIdRegimenes());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEmpresas();
         result = 37 * result + this.getIdRegimenes();
         return result;
   }   


}


