package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * ErroresGeneracionRetenciones generated by hbm2java
 */
public class ErroresGeneracionRetenciones  implements java.io.Serializable {


     private Integer id;
     private DocumentosRecibidosRetenciones documentosRecibidosRetenciones;
     private String stage;
     private String description;
     private String detailedDescription;

    public ErroresGeneracionRetenciones() {
    }

	
    public ErroresGeneracionRetenciones(DocumentosRecibidosRetenciones documentosRecibidosRetenciones, String stage, String description) {
        this.documentosRecibidosRetenciones = documentosRecibidosRetenciones;
        this.stage = stage;
        this.description = description;
    }
    public ErroresGeneracionRetenciones(DocumentosRecibidosRetenciones documentosRecibidosRetenciones, String stage, String description, String detailedDescription) {
       this.documentosRecibidosRetenciones = documentosRecibidosRetenciones;
       this.stage = stage;
       this.description = description;
       this.detailedDescription = detailedDescription;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public DocumentosRecibidosRetenciones getDocumentosRecibidosRetenciones() {
        return this.documentosRecibidosRetenciones;
    }
    
    public void setDocumentosRecibidosRetenciones(DocumentosRecibidosRetenciones documentosRecibidosRetenciones) {
        this.documentosRecibidosRetenciones = documentosRecibidosRetenciones;
    }
    public String getStage() {
        return this.stage;
    }
    
    public void setStage(String stage) {
        this.stage = stage;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getDetailedDescription() {
        return this.detailedDescription;
    }
    
    public void setDetailedDescription(String detailedDescription) {
        this.detailedDescription = detailedDescription;
    }




}


