package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FoliosEmpresas generated by hbm2java
 */
public class FoliosEmpresas  implements java.io.Serializable {


     private Integer idFolioserie;
     private Empresas empresas;
     private TiposCfd tiposCfd;
     private String serie;
     private long inicio;
     private long final_;
     private Long numeroAprobacion;
     private Integer anioAprobacion;
     private String estado;
     private Date ultimaVerificacion;
     private Long ultimoFolioBloque;
     private BigDecimal tamanioBloque;
     private Set foliosHistorials = new HashSet(0);

    public FoliosEmpresas() {
    }

	
    public FoliosEmpresas(Empresas empresas, long inicio, long final_, Date ultimaVerificacion) {
        this.empresas = empresas;
        this.inicio = inicio;
        this.final_ = final_;
        this.ultimaVerificacion = ultimaVerificacion;
    }
    public FoliosEmpresas(Empresas empresas, TiposCfd tiposCfd, String serie, long inicio, long final_, Long numeroAprobacion, Integer anioAprobacion, String estado, Date ultimaVerificacion, Long ultimoFolioBloque, BigDecimal tamanioBloque, Set foliosHistorials) {
       this.empresas = empresas;
       this.tiposCfd = tiposCfd;
       this.serie = serie;
       this.inicio = inicio;
       this.final_ = final_;
       this.numeroAprobacion = numeroAprobacion;
       this.anioAprobacion = anioAprobacion;
       this.estado = estado;
       this.ultimaVerificacion = ultimaVerificacion;
       this.ultimoFolioBloque = ultimoFolioBloque;
       this.tamanioBloque = tamanioBloque;
       this.foliosHistorials = foliosHistorials;
    }
   
    public Integer getIdFolioserie() {
        return this.idFolioserie;
    }
    
    public void setIdFolioserie(Integer idFolioserie) {
        this.idFolioserie = idFolioserie;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }
    public long getInicio() {
        return this.inicio;
    }
    
    public void setInicio(long inicio) {
        this.inicio = inicio;
    }
    public long getFinal_() {
        return this.final_;
    }
    
    public void setFinal_(long final_) {
        this.final_ = final_;
    }
    public Long getNumeroAprobacion() {
        return this.numeroAprobacion;
    }
    
    public void setNumeroAprobacion(Long numeroAprobacion) {
        this.numeroAprobacion = numeroAprobacion;
    }
    public Integer getAnioAprobacion() {
        return this.anioAprobacion;
    }
    
    public void setAnioAprobacion(Integer anioAprobacion) {
        this.anioAprobacion = anioAprobacion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Date getUltimaVerificacion() {
        return this.ultimaVerificacion;
    }
    
    public void setUltimaVerificacion(Date ultimaVerificacion) {
        this.ultimaVerificacion = ultimaVerificacion;
    }
    public Long getUltimoFolioBloque() {
        return this.ultimoFolioBloque;
    }
    
    public void setUltimoFolioBloque(Long ultimoFolioBloque) {
        this.ultimoFolioBloque = ultimoFolioBloque;
    }
    public BigDecimal getTamanioBloque() {
        return this.tamanioBloque;
    }
    
    public void setTamanioBloque(BigDecimal tamanioBloque) {
        this.tamanioBloque = tamanioBloque;
    }
    public Set getFoliosHistorials() {
        return this.foliosHistorials;
    }
    
    public void setFoliosHistorials(Set foliosHistorials) {
        this.foliosHistorials = foliosHistorials;
    }




}


