package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * FoliosHistorial generated by hbm2java
 */
public class FoliosHistorial  implements java.io.Serializable {


     private Integer idFolio;
     private FoliosEmpresas foliosEmpresas;
     private long folio;

    public FoliosHistorial() {
    }

    public FoliosHistorial(FoliosEmpresas foliosEmpresas, long folio) {
       this.foliosEmpresas = foliosEmpresas;
       this.folio = folio;
    }
   
    public Integer getIdFolio() {
        return this.idFolio;
    }
    
    public void setIdFolio(Integer idFolio) {
        this.idFolio = idFolio;
    }
    public FoliosEmpresas getFoliosEmpresas() {
        return this.foliosEmpresas;
    }
    
    public void setFoliosEmpresas(FoliosEmpresas foliosEmpresas) {
        this.foliosEmpresas = foliosEmpresas;
    }
    public long getFolio() {
        return this.folio;
    }
    
    public void setFolio(long folio) {
        this.folio = folio;
    }




}


