package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MetodosRecepcion generated by hbm2java
 */
public class MetodosRecepcion  implements java.io.Serializable {


     private Integer idMetodo;
     private String nombre;
     private String descripcion;
     private Set usuariosRecepcionRetencioneses = new HashSet(0);

    public MetodosRecepcion() {
    }

	
    public MetodosRecepcion(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public MetodosRecepcion(String nombre, String descripcion, Set usuariosRecepcionRetencioneses) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.usuariosRecepcionRetencioneses = usuariosRecepcionRetencioneses;
    }
   
    public Integer getIdMetodo() {
        return this.idMetodo;
    }
    
    public void setIdMetodo(Integer idMetodo) {
        this.idMetodo = idMetodo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuariosRecepcionRetencioneses() {
        return this.usuariosRecepcionRetencioneses;
    }
    
    public void setUsuariosRecepcionRetencioneses(Set usuariosRecepcionRetencioneses) {
        this.usuariosRecepcionRetencioneses = usuariosRecepcionRetencioneses;
    }




}


