package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * ReceptorRetenciones generated by hbm2java
 */
public class ReceptorRetenciones  implements java.io.Serializable {


     private int idCfdRetencion;
     private CfdsRetenciones cfdsRetenciones;
     private String nacionalidad;
     private String razonSocial;
     private String rfc;
     private String curp;

    public ReceptorRetenciones() {
    }

	
    public ReceptorRetenciones(int idCfdRetencion, CfdsRetenciones cfdsRetenciones, String nacionalidad) {
        this.idCfdRetencion = idCfdRetencion;
        this.cfdsRetenciones = cfdsRetenciones;
        this.nacionalidad = nacionalidad;
    }
    public ReceptorRetenciones(int idCfdRetencion, CfdsRetenciones cfdsRetenciones, String nacionalidad, String razonSocial, String rfc, String curp) {
       this.idCfdRetencion = idCfdRetencion;
       this.cfdsRetenciones = cfdsRetenciones;
       this.nacionalidad = nacionalidad;
       this.razonSocial = razonSocial;
       this.rfc = rfc;
       this.curp = curp;
    }
   
    public int getIdCfdRetencion() {
        return this.idCfdRetencion;
    }
    
    public void setIdCfdRetencion(int idCfdRetencion) {
        this.idCfdRetencion = idCfdRetencion;
    }
    public CfdsRetenciones getCfdsRetenciones() {
        return this.cfdsRetenciones;
    }
    
    public void setCfdsRetenciones(CfdsRetenciones cfdsRetenciones) {
        this.cfdsRetenciones = cfdsRetenciones;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCurp() {
        return this.curp;
    }
    
    public void setCurp(String curp) {
        this.curp = curp;
    }




}


