package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * Regimenes generated by hbm2java
 */
public class Regimenes  implements java.io.Serializable {


     private Integer idRegimen;
     private Integer idEmpresa;
     private String regimen;
     private String tipoPersona;
     private String ligaInformacion;

    public Regimenes() {
    }

	
    public Regimenes(String regimen, String tipoPersona) {
        this.regimen = regimen;
        this.tipoPersona = tipoPersona;
    }
    public Regimenes(Integer idEmpresa, String regimen, String tipoPersona, String ligaInformacion) {
       this.idEmpresa = idEmpresa;
       this.regimen = regimen;
       this.tipoPersona = tipoPersona;
       this.ligaInformacion = ligaInformacion;
    }
   
    public Integer getIdRegimen() {
        return this.idRegimen;
    }
    
    public void setIdRegimen(Integer idRegimen) {
        this.idRegimen = idRegimen;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getRegimen() {
        return this.regimen;
    }
    
    public void setRegimen(String regimen) {
        this.regimen = regimen;
    }
    public String getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(String tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public String getLigaInformacion() {
        return this.ligaInformacion;
    }
    
    public void setLigaInformacion(String ligaInformacion) {
        this.ligaInformacion = ligaInformacion;
    }




}


