package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * RetencionesPlantillas generated by hbm2java
 */
public class RetencionesPlantillas  implements java.io.Serializable {


     private Integer idRetencionesPlantilla;
     private TiposCfdRetenciones tiposCfdRetenciones;
     private String path;
     private boolean isDefault;
     private Date creationDate;
     private Date fechaModificacion;
     private Set cfdsRetencioneses = new HashSet(0);

    public RetencionesPlantillas() {
    }

	
    public RetencionesPlantillas(TiposCfdRetenciones tiposCfdRetenciones, String path, boolean isDefault, Date creationDate) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
        this.path = path;
        this.isDefault = isDefault;
        this.creationDate = creationDate;
    }
    public RetencionesPlantillas(TiposCfdRetenciones tiposCfdRetenciones, String path, boolean isDefault, Date creationDate, Date fechaModificacion, Set cfdsRetencioneses) {
       this.tiposCfdRetenciones = tiposCfdRetenciones;
       this.path = path;
       this.isDefault = isDefault;
       this.creationDate = creationDate;
       this.fechaModificacion = fechaModificacion;
       this.cfdsRetencioneses = cfdsRetencioneses;
    }
   
    public Integer getIdRetencionesPlantilla() {
        return this.idRetencionesPlantilla;
    }
    
    public void setIdRetencionesPlantilla(Integer idRetencionesPlantilla) {
        this.idRetencionesPlantilla = idRetencionesPlantilla;
    }
    public TiposCfdRetenciones getTiposCfdRetenciones() {
        return this.tiposCfdRetenciones;
    }
    
    public void setTiposCfdRetenciones(TiposCfdRetenciones tiposCfdRetenciones) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public boolean isIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(boolean isDefault) {
        this.isDefault = isDefault;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Set getCfdsRetencioneses() {
        return this.cfdsRetencioneses;
    }
    
    public void setCfdsRetencioneses(Set cfdsRetencioneses) {
        this.cfdsRetencioneses = cfdsRetencioneses;
    }




}


