package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SucursalesXslt generated by hbm2java
 */
public class SucursalesXslt  implements java.io.Serializable {


     private Integer idPlantilla;
     private TiposCfd tiposCfd;
     private Integer idSucursal;
     private String xslt;
     private String margenes;
     private String tamanio;
     private String encabezado;
     private Boolean reload;
     private Boolean reloadDelivery;
     private Integer anchoHtml;
     private Boolean esDefault;
     private Date fechaAlta;
     private String idExterno;
     private boolean engineJasper;
     private Integer idConfiguracion;
     private Date fechaModificacion;

    public SucursalesXslt() {
    }

	
    public SucursalesXslt(TiposCfd tiposCfd, Date fechaAlta, boolean engineJasper) {
        this.tiposCfd = tiposCfd;
        this.fechaAlta = fechaAlta;
        this.engineJasper = engineJasper;
    }
    public SucursalesXslt(TiposCfd tiposCfd, Integer idSucursal, String xslt, String margenes, String tamanio, String encabezado, Boolean reload, Boolean reloadDelivery, Integer anchoHtml, Boolean esDefault, Date fechaAlta, String idExterno, boolean engineJasper, Integer idConfiguracion, Date fechaModificacion) {
       this.tiposCfd = tiposCfd;
       this.idSucursal = idSucursal;
       this.xslt = xslt;
       this.margenes = margenes;
       this.tamanio = tamanio;
       this.encabezado = encabezado;
       this.reload = reload;
       this.reloadDelivery = reloadDelivery;
       this.anchoHtml = anchoHtml;
       this.esDefault = esDefault;
       this.fechaAlta = fechaAlta;
       this.idExterno = idExterno;
       this.engineJasper = engineJasper;
       this.idConfiguracion = idConfiguracion;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Integer getIdPlantilla() {
        return this.idPlantilla;
    }
    
    public void setIdPlantilla(Integer idPlantilla) {
        this.idPlantilla = idPlantilla;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public Integer getIdSucursal() {
        return this.idSucursal;
    }
    
    public void setIdSucursal(Integer idSucursal) {
        this.idSucursal = idSucursal;
    }
    public String getXslt() {
        return this.xslt;
    }
    
    public void setXslt(String xslt) {
        this.xslt = xslt;
    }
    public String getMargenes() {
        return this.margenes;
    }
    
    public void setMargenes(String margenes) {
        this.margenes = margenes;
    }
    public String getTamanio() {
        return this.tamanio;
    }
    
    public void setTamanio(String tamanio) {
        this.tamanio = tamanio;
    }
    public String getEncabezado() {
        return this.encabezado;
    }
    
    public void setEncabezado(String encabezado) {
        this.encabezado = encabezado;
    }
    public Boolean getReload() {
        return this.reload;
    }
    
    public void setReload(Boolean reload) {
        this.reload = reload;
    }
    public Boolean getReloadDelivery() {
        return this.reloadDelivery;
    }
    
    public void setReloadDelivery(Boolean reloadDelivery) {
        this.reloadDelivery = reloadDelivery;
    }
    public Integer getAnchoHtml() {
        return this.anchoHtml;
    }
    
    public void setAnchoHtml(Integer anchoHtml) {
        this.anchoHtml = anchoHtml;
    }
    public Boolean getEsDefault() {
        return this.esDefault;
    }
    
    public void setEsDefault(Boolean esDefault) {
        this.esDefault = esDefault;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public String getIdExterno() {
        return this.idExterno;
    }
    
    public void setIdExterno(String idExterno) {
        this.idExterno = idExterno;
    }
    public boolean isEngineJasper() {
        return this.engineJasper;
    }
    
    public void setEngineJasper(boolean engineJasper) {
        this.engineJasper = engineJasper;
    }
    public Integer getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(Integer idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


