package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * TiposCfdComplementosId generated by hbm2java
 */
public class TiposCfdComplementosId  implements java.io.Serializable {


     private int idComplemento;
     private int idTipocfd;

    public TiposCfdComplementosId() {
    }

    public TiposCfdComplementosId(int idComplemento, int idTipocfd) {
       this.idComplemento = idComplemento;
       this.idTipocfd = idTipocfd;
    }
   
    public int getIdComplemento() {
        return this.idComplemento;
    }
    
    public void setIdComplemento(int idComplemento) {
        this.idComplemento = idComplemento;
    }
    public int getIdTipocfd() {
        return this.idTipocfd;
    }
    
    public void setIdTipocfd(int idTipocfd) {
        this.idTipocfd = idTipocfd;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TiposCfdComplementosId) ) return false;
		 TiposCfdComplementosId castOther = ( TiposCfdComplementosId ) other; 
         
		 return (this.getIdComplemento()==castOther.getIdComplemento())
 && (this.getIdTipocfd()==castOther.getIdTipocfd());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdComplemento();
         result = 37 * result + this.getIdTipocfd();
         return result;
   }   


}


