package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposCfd generated by hbm2java
 */
public class TiposCfd  implements java.io.Serializable {


     private Integer idTipocfd;
     private CatalogoPlantillas catalogoPlantillas;
     private Empresas empresas;
     private ConectorAdaptador conectorAdaptador;
     private String nombre;
     private String tipo;
     private String stylusConector;
     private String xsltToTralix;
     private boolean modoManual;
     private boolean reload;
     private String encoding;
     private String modo;
     private String tipoUso;
     private boolean produccion;
     private Integer linkIdTipocfd;
     private Integer versionCfd;
     private Set clientesAddendases = new HashSet(0);
     private Set usuariosRecepcions = new HashSet(0);
     private Set sucursalesXslts = new HashSet(0);
     private Set foliosEmpresases = new HashSet(0);
     private Set documentosRecibidoses = new HashSet(0);
     private Set cfdses = new HashSet(0);
     private Set tiposCfdComplementoses = new HashSet(0);

    public TiposCfd() {
    }

	
    public TiposCfd(Empresas empresas, boolean modoManual, boolean reload, String tipoUso, boolean produccion) {
        this.empresas = empresas;
        this.modoManual = modoManual;
        this.reload = reload;
        this.tipoUso = tipoUso;
        this.produccion = produccion;
    }
    public TiposCfd(CatalogoPlantillas catalogoPlantillas, Empresas empresas, ConectorAdaptador conectorAdaptador, String nombre, String tipo, String stylusConector, String xsltToTralix, boolean modoManual, boolean reload, String encoding, String modo, String tipoUso, boolean produccion, Integer linkIdTipocfd, Integer versionCfd, Set clientesAddendases, Set usuariosRecepcions, Set sucursalesXslts, Set foliosEmpresases, Set documentosRecibidoses, Set cfdses, Set tiposCfdComplementoses) {
       this.catalogoPlantillas = catalogoPlantillas;
       this.empresas = empresas;
       this.conectorAdaptador = conectorAdaptador;
       this.nombre = nombre;
       this.tipo = tipo;
       this.stylusConector = stylusConector;
       this.xsltToTralix = xsltToTralix;
       this.modoManual = modoManual;
       this.reload = reload;
       this.encoding = encoding;
       this.modo = modo;
       this.tipoUso = tipoUso;
       this.produccion = produccion;
       this.linkIdTipocfd = linkIdTipocfd;
       this.versionCfd = versionCfd;
       this.clientesAddendases = clientesAddendases;
       this.usuariosRecepcions = usuariosRecepcions;
       this.sucursalesXslts = sucursalesXslts;
       this.foliosEmpresases = foliosEmpresases;
       this.documentosRecibidoses = documentosRecibidoses;
       this.cfdses = cfdses;
       this.tiposCfdComplementoses = tiposCfdComplementoses;
    }
   
    public Integer getIdTipocfd() {
        return this.idTipocfd;
    }
    
    public void setIdTipocfd(Integer idTipocfd) {
        this.idTipocfd = idTipocfd;
    }
    public CatalogoPlantillas getCatalogoPlantillas() {
        return this.catalogoPlantillas;
    }
    
    public void setCatalogoPlantillas(CatalogoPlantillas catalogoPlantillas) {
        this.catalogoPlantillas = catalogoPlantillas;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    public ConectorAdaptador getConectorAdaptador() {
        return this.conectorAdaptador;
    }
    
    public void setConectorAdaptador(ConectorAdaptador conectorAdaptador) {
        this.conectorAdaptador = conectorAdaptador;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getStylusConector() {
        return this.stylusConector;
    }
    
    public void setStylusConector(String stylusConector) {
        this.stylusConector = stylusConector;
    }
    public String getXsltToTralix() {
        return this.xsltToTralix;
    }
    
    public void setXsltToTralix(String xsltToTralix) {
        this.xsltToTralix = xsltToTralix;
    }
    public boolean isModoManual() {
        return this.modoManual;
    }
    
    public void setModoManual(boolean modoManual) {
        this.modoManual = modoManual;
    }
    public boolean isReload() {
        return this.reload;
    }
    
    public void setReload(boolean reload) {
        this.reload = reload;
    }
    public String getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }
    public String getModo() {
        return this.modo;
    }
    
    public void setModo(String modo) {
        this.modo = modo;
    }
    public String getTipoUso() {
        return this.tipoUso;
    }
    
    public void setTipoUso(String tipoUso) {
        this.tipoUso = tipoUso;
    }
    public boolean isProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(boolean produccion) {
        this.produccion = produccion;
    }
    public Integer getLinkIdTipocfd() {
        return this.linkIdTipocfd;
    }
    
    public void setLinkIdTipocfd(Integer linkIdTipocfd) {
        this.linkIdTipocfd = linkIdTipocfd;
    }
    public Integer getVersionCfd() {
        return this.versionCfd;
    }
    
    public void setVersionCfd(Integer versionCfd) {
        this.versionCfd = versionCfd;
    }
    public Set getClientesAddendases() {
        return this.clientesAddendases;
    }
    
    public void setClientesAddendases(Set clientesAddendases) {
        this.clientesAddendases = clientesAddendases;
    }
    public Set getUsuariosRecepcions() {
        return this.usuariosRecepcions;
    }
    
    public void setUsuariosRecepcions(Set usuariosRecepcions) {
        this.usuariosRecepcions = usuariosRecepcions;
    }
    public Set getSucursalesXslts() {
        return this.sucursalesXslts;
    }
    
    public void setSucursalesXslts(Set sucursalesXslts) {
        this.sucursalesXslts = sucursalesXslts;
    }
    public Set getFoliosEmpresases() {
        return this.foliosEmpresases;
    }
    
    public void setFoliosEmpresases(Set foliosEmpresases) {
        this.foliosEmpresases = foliosEmpresases;
    }
    public Set getDocumentosRecibidoses() {
        return this.documentosRecibidoses;
    }
    
    public void setDocumentosRecibidoses(Set documentosRecibidoses) {
        this.documentosRecibidoses = documentosRecibidoses;
    }
    public Set getCfdses() {
        return this.cfdses;
    }
    
    public void setCfdses(Set cfdses) {
        this.cfdses = cfdses;
    }
    public Set getTiposCfdComplementoses() {
        return this.tiposCfdComplementoses;
    }
    
    public void setTiposCfdComplementoses(Set tiposCfdComplementoses) {
        this.tiposCfdComplementoses = tiposCfdComplementoses;
    }




}


