package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TiposCfdRetenciones generated by hbm2java
 */
public class TiposCfdRetenciones  implements java.io.Serializable {


     private Integer id;
     private Empresas empresas;
     
     private ConectorAdaptadorRetenciones conectorAdaptadorRetenciones;
     private String nombre;
     private String encoding;
     private boolean produccion;
     private Set documentosRecibidosRetencioneses = new HashSet(0);
     private Set usuariosRecepcionRetencioneses = new HashSet(0);
     private Set cfdsRetencionesTests = new HashSet(0);
     private Set retencionesPlantillases = new HashSet(0);

    public TiposCfdRetenciones() {
    }

	
    public TiposCfdRetenciones(Empresas empresas, ConectorAdaptadorRetenciones conectorAdaptadorRetenciones, boolean produccion) {
        this.empresas = empresas;
        this.conectorAdaptadorRetenciones = conectorAdaptadorRetenciones;
        this.produccion = produccion;
    }
    public TiposCfdRetenciones(Empresas empresas, ComplementosRetenciones complementosRetenciones, ConectorAdaptadorRetenciones conectorAdaptadorRetenciones, String nombre, String encoding, boolean produccion, Set documentosRecibidosRetencioneses, Set usuariosRecepcionRetencioneses, Set cfdsRetencionesTests, Set retencionesPlantillases) {
       this.empresas = empresas;
       
       this.conectorAdaptadorRetenciones = conectorAdaptadorRetenciones;
       this.nombre = nombre;
       this.encoding = encoding;
       this.produccion = produccion;
       this.documentosRecibidosRetencioneses = documentosRecibidosRetencioneses;
       this.usuariosRecepcionRetencioneses = usuariosRecepcionRetencioneses;
       this.cfdsRetencionesTests = cfdsRetencionesTests;
       this.retencionesPlantillases = retencionesPlantillases;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Empresas getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Empresas empresas) {
        this.empresas = empresas;
    }
    
    public ConectorAdaptadorRetenciones getConectorAdaptadorRetenciones() {
        return this.conectorAdaptadorRetenciones;
    }
    
    public void setConectorAdaptadorRetenciones(ConectorAdaptadorRetenciones conectorAdaptadorRetenciones) {
        this.conectorAdaptadorRetenciones = conectorAdaptadorRetenciones;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEncoding() {
        return this.encoding;
    }
    
    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }
    public boolean isProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(boolean produccion) {
        this.produccion = produccion;
    }
    public Set getDocumentosRecibidosRetencioneses() {
        return this.documentosRecibidosRetencioneses;
    }
    
    public void setDocumentosRecibidosRetencioneses(Set documentosRecibidosRetencioneses) {
        this.documentosRecibidosRetencioneses = documentosRecibidosRetencioneses;
    }
    public Set getUsuariosRecepcionRetencioneses() {
        return this.usuariosRecepcionRetencioneses;
    }
    
    public void setUsuariosRecepcionRetencioneses(Set usuariosRecepcionRetencioneses) {
        this.usuariosRecepcionRetencioneses = usuariosRecepcionRetencioneses;
    }
    public Set getCfdsRetencionesTests() {
        return this.cfdsRetencionesTests;
    }
    
    public void setCfdsRetencionesTests(Set cfdsRetencionesTests) {
        this.cfdsRetencionesTests = cfdsRetencionesTests;
    }
    public Set getRetencionesPlantillases() {
        return this.retencionesPlantillases;
    }
    
    public void setRetencionesPlantillases(Set retencionesPlantillases) {
        this.retencionesPlantillases = retencionesPlantillases;
    }




}


