package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * TiposCfdComplementos generated by hbm2java
 */
public class TiposCfdComplementos  implements java.io.Serializable {


     private TiposCfdComplementosId id;
     private Complementos complementos;
     private TiposCfd tiposCfd;
     private String adaptador;
     private boolean reloadAdaptador;

    public TiposCfdComplementos() {
    }

    public TiposCfdComplementos(TiposCfdComplementosId id, Complementos complementos, TiposCfd tiposCfd, String adaptador, boolean reloadAdaptador) {
       this.id = id;
       this.complementos = complementos;
       this.tiposCfd = tiposCfd;
       this.adaptador = adaptador;
       this.reloadAdaptador = reloadAdaptador;
    }
   
    public TiposCfdComplementosId getId() {
        return this.id;
    }
    
    public void setId(TiposCfdComplementosId id) {
        this.id = id;
    }
    public Complementos getComplementos() {
        return this.complementos;
    }
    
    public void setComplementos(Complementos complementos) {
        this.complementos = complementos;
    }
    public TiposCfd getTiposCfd() {
        return this.tiposCfd;
    }
    
    public void setTiposCfd(TiposCfd tiposCfd) {
        this.tiposCfd = tiposCfd;
    }
    public String getAdaptador() {
        return this.adaptador;
    }
    
    public void setAdaptador(String adaptador) {
        this.adaptador = adaptador;
    }
    public boolean isReloadAdaptador() {
        return this.reloadAdaptador;
    }
    
    public void setReloadAdaptador(boolean reloadAdaptador) {
        this.reloadAdaptador = reloadAdaptador;
    }




}


