package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UsuariosRecepcionRetenciones generated by hbm2java
 */
public class UsuariosRecepcionRetenciones  implements java.io.Serializable {


     private Integer id;
     private Sucursales sucursales;
     private TiposCfdRetenciones tiposCfdRetenciones;
     private String usuario;
     private String passwd;
     private String homeftp;
     private String homesftp;
     private String oldPassword;
     private Set metodosRecepcions = new HashSet(0);

    public UsuariosRecepcionRetenciones() {
    }

	
    public UsuariosRecepcionRetenciones(Sucursales sucursales, String usuario, String passwd) {
        this.sucursales = sucursales;
        this.usuario = usuario;
        this.passwd = passwd;
    }
    public UsuariosRecepcionRetenciones(Sucursales sucursales, TiposCfdRetenciones tiposCfdRetenciones, String usuario, String passwd, String homeftp, String homesftp, String oldPassword, Set metodosRecepcions) {
       this.sucursales = sucursales;
       this.tiposCfdRetenciones = tiposCfdRetenciones;
       this.usuario = usuario;
       this.passwd = passwd;
       this.homeftp = homeftp;
       this.homesftp = homesftp;
       this.oldPassword = oldPassword;
       this.metodosRecepcions = metodosRecepcions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sucursales getSucursales() {
        return this.sucursales;
    }
    
    public void setSucursales(Sucursales sucursales) {
        this.sucursales = sucursales;
    }
    public TiposCfdRetenciones getTiposCfdRetenciones() {
        return this.tiposCfdRetenciones;
    }
    
    public void setTiposCfdRetenciones(TiposCfdRetenciones tiposCfdRetenciones) {
        this.tiposCfdRetenciones = tiposCfdRetenciones;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPasswd() {
        return this.passwd;
    }
    
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }
    public String getHomeftp() {
        return this.homeftp;
    }
    
    public void setHomeftp(String homeftp) {
        this.homeftp = homeftp;
    }
    public String getHomesftp() {
        return this.homesftp;
    }
    
    public void setHomesftp(String homesftp) {
        this.homesftp = homesftp;
    }
    public String getOldPassword() {
        return this.oldPassword;
    }
    
    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }
    public Set getMetodosRecepcions() {
        return this.metodosRecepcions;
    }
    
    public void setMetodosRecepcions(Set metodosRecepcions) {
        this.metodosRecepcions = metodosRecepcions;
    }




}


