package com.iq.pojos.xsa;
// Generated 05-may-2020 13:56:01 by Hibernate Tools 3.2.1.GA



/**
 * XmlsRetencionesTest generated by hbm2java
 */
public class XmlsRetencionesTest  implements java.io.Serializable {


     private Integer idCfdRetencionTest;
     private CfdsRetencionesTest cfdsRetencionesTest;
     private String xmlSat;
     private String xmlTralix;

    public XmlsRetencionesTest() {
    }

    public XmlsRetencionesTest(CfdsRetencionesTest cfdsRetencionesTest, String xmlSat, String xmlTralix) {
       this.cfdsRetencionesTest = cfdsRetencionesTest;
       this.xmlSat = xmlSat;
       this.xmlTralix = xmlTralix;
    }
   
    public Integer getIdCfdRetencionTest() {
        return this.idCfdRetencionTest;
    }
    
    public void setIdCfdRetencionTest(Integer idCfdRetencionTest) {
        this.idCfdRetencionTest = idCfdRetencionTest;
    }
    public CfdsRetencionesTest getCfdsRetencionesTest() {
        return this.cfdsRetencionesTest;
    }
    
    public void setCfdsRetencionesTest(CfdsRetencionesTest cfdsRetencionesTest) {
        this.cfdsRetencionesTest = cfdsRetencionesTest;
    }
    public String getXmlSat() {
        return this.xmlSat;
    }
    
    public void setXmlSat(String xmlSat) {
        this.xmlSat = xmlSat;
    }
    public String getXmlTralix() {
        return this.xmlTralix;
    }
    
    public void setXmlTralix(String xmlTralix) {
        this.xmlTralix = xmlTralix;
    }




}


